export const MOCK_PROFILES = [
  {
    id: "m1",
    username: "Elena",
    pseudo: "Elena",
    age: 24,
    city: "Paris",
    distance: "2 km",
    category: "Féminine",
    genderIdentity: "PERSONNE_FEMININE",
    description: "Douce, élégante et discrète. Je recherche des rencontres sincères dans un cadre premium.",
    images: [],
    verified: true,
    isVerified: true,
    online: true,
    onlineStatus: true,
    premium: true,
    isPremium: true,
    tags: ["Discrète", "Élégante", "Paris centre"],
    languages: ["Français", "Anglais"],
    lastSeen: "À l'instant",
    isNew: false,
    availabilityLabel: "Maintenant",
    intentions: ["verre d'abord", "rencontre ce soir", "discret"],
    isDiscreet: false,
    courtesyBadges: ["Profil courtois", "Vérifié"]
  },
  {
    id: "m2",
    username: "Victoria",
    pseudo: "Victoria",
    age: 28,
    city: "Lyon",
    distance: "5 km",
    category: "Trans",
    genderIdentity: "FEMME_TRANS",
    description: "Passionnée de mode et d'art. J'aime les discussions profondes et les lieux raffinés.",
    images: [],
    verified: true,
    isVerified: true,
    online: false,
    onlineStatus: false,
    premium: false,
    isPremium: false,
    tags: ["Art", "Mode", "Spontanée"],
    languages: ["Français"],
    lastSeen: "Il y a 2h",
    isNew: false,
    availabilityLabel: "Maintenant",
    intentions: ["verre d'abord", "rencontre ce soir", "discret"],
    isDiscreet: false,
    courtesyBadges: ["Profil courtois", "Vérifié"]
  },
  {
    id: "m3",
    username: "Chloé",
    pseudo: "Chloé",
    age: 22,
    city: "Bordeaux",
    distance: "10 km",
    category: "Féminine",
    genderIdentity: "PERSONNE_FEMININE",
    description: "Nouvelle ici ! Je cherche à découvrir de nouvelles personnes avec bienveillance.",
    images: [],
    verified: false,
    isVerified: false,
    online: true,
    onlineStatus: true,
    premium: true,
    isPremium: true,
    tags: ["Nouvelle", "Souriante", "Pétillante"],
    languages: ["Français", "Espagnol"],
    lastSeen: "En ligne",
    isNew: true,
    availabilityLabel: "Ce soir",
    intentions: ["discuter d'abord", "uniquement si feeling"],
    isDiscreet: true,
    courtesyBadges: ["Réponse rapide", "Vérifié"]
  },
  {
    id: "m4",
    username: "Alya",
    pseudo: "Alya",
    age: 26,
    city: "Cannes",
    distance: "À proximité",
    category: "Trans",
    genderIdentity: "FEMME_TRANS",
    description: "Solaire et ambitieuse. Je voyage beaucoup mais j'apprécie les moments simples à deux.",
    images: [],
    verified: true,
    isVerified: true,
    online: true,
    onlineStatus: true,
    premium: true,
    isPremium: true,
    tags: ["Voyage", "Ambitieuse", "Sud"],
    languages: ["Français", "Italien"],
    lastSeen: "En ligne",
    isNew: false,
    availabilityLabel: "Maintenant",
    intentions: ["verre d'abord", "rencontre ce soir", "discret"],
    isDiscreet: false,
    courtesyBadges: ["Profil courtois", "Vérifié"]
  },
  {
    id: "m5",
    username: "Juliette",
    pseudo: "Juliette",
    age: 31,
    city: "Strasbourg",
    distance: "15 km",
    category: "Femme Cis",
    genderIdentity: "FEMME",
    description: "Un brin mystérieuse. J'aime l'élégance, le bon vin et les conversations sans filtre.",
    images: [],
    verified: true,
    isVerified: true,
    online: false,
    onlineStatus: false,
    premium: false,
    isPremium: false,
    tags: ["Épicurienne", "Mystère", "Sincère"],
    languages: ["Français", "Allemand"],
    lastSeen: "Il y a 1 jour",
    isNew: false,
    availabilityLabel: "Maintenant",
    intentions: ["verre d'abord", "rencontre ce soir", "discret"],
    isDiscreet: false,
    courtesyBadges: ["Profil courtois", "Vérifié"]
  },
  {
    id: "m6",
    username: "Romy",
    pseudo: "Romy",
    age: 23,
    city: "Lille",
    distance: "1 km",
    category: "Féminine",
    genderIdentity: "PERSONNE_FEMININE",
    description: "Douceur et malice. Étudiante en design, je suis ici pour des rencontres inspirantes.",
    images: [],
    verified: false,
    isVerified: false,
    online: true,
    onlineStatus: true,
    premium: false,
    isPremium: false,
    tags: ["Design", "Créative", "Noctambule"],
    languages: ["Français"],
    lastSeen: "En ligne",
    isNew: true,
    availabilityLabel: "Ce soir",
    intentions: ["discuter d'abord", "uniquement si feeling"],
    isDiscreet: true,
    courtesyBadges: ["Réponse rapide", "Vérifié"]
  },
  {
    id: "m7",
    username: "Sasha",
    pseudo: "Sasha",
    age: 27,
    city: "Marseille",
    distance: "3 km",
    category: "Travesti",
    genderIdentity: "TRAVESTI",
    description: "J'assume ma part de féminité avec élégance. Discrétion absolue exigée et offerte.",
    images: [],
    verified: true,
    isVerified: true,
    online: true,
    onlineStatus: true,
    premium: true,
    isPremium: true,
    tags: ["Discrétion", "Charme", "Respect"],
    languages: ["Français", "Anglais"],
    lastSeen: "En ligne",
    isNew: false,
    availabilityLabel: "Maintenant",
    intentions: ["verre d'abord", "rencontre ce soir", "discret"],
    isDiscreet: false,
    courtesyBadges: ["Profil courtois", "Vérifié"]
  },
  {
    id: "m8",
    username: "Eva",
    pseudo: "Eva",
    age: 29,
    city: "Paris",
    distance: "500 m",
    category: "Trans",
    genderIdentity: "FEMME_TRANS",
    description: "Parisienne jusqu'au bout des ongles. Je cherche l'étincelle et la connexion intellectuelle.",
    images: [],
    verified: true,
    isVerified: true,
    online: false,
    onlineStatus: false,
    premium: true,
    isPremium: true,
    tags: ["Parisienne", "Cinéma", "Intense"],
    languages: ["Français"],
    lastSeen: "Hier",
    isNew: false,
    availabilityLabel: "Maintenant",
    intentions: ["verre d'abord", "rencontre ce soir", "discret"],
    isDiscreet: false,
    courtesyBadges: ["Profil courtois", "Vérifié"]
  },
  {
    id: "m9",
    username: "Mia & Léo",
    pseudo: "Mia & Léo",
    age: 32,
    city: "Nantes",
    distance: "20 km",
    category: "Couple",
    genderIdentity: "COUPLE",
    description: "Couple ouvert, curieux et respectueux. Nous cherchons une troisième personne pour partager un verre et plus si affinités.",
    images: [],
    verified: true,
    isVerified: true,
    online: true,
    onlineStatus: true,
    premium: false,
    isPremium: false,
    tags: ["Ouverture", "Respect", "Complices"],
    languages: ["Français"],
    lastSeen: "À l'instant",
    isNew: true,
    availabilityLabel: "Ce soir",
    intentions: ["discuter d'abord", "uniquement si feeling"],
    isDiscreet: true,
    courtesyBadges: ["Réponse rapide", "Vérifié"]
  },
  {
    id: "m10",
    username: "Inès",
    pseudo: "Inès",
    age: 25,
    city: "Nice",
    distance: "12 km",
    category: "Féminine",
    genderIdentity: "PERSONNE_FEMININE",
    description: "Soleil et spontanéité. J'adore les imprévus et les belles soirées d'été.",
    images: [],
    verified: false,
    isVerified: false,
    online: false,
    onlineStatus: false,
    premium: false,
    isPremium: false,
    tags: ["Soleil", "Fête", "Douceur"],
    languages: ["Français", "Italien"],
    lastSeen: "Il y a 5h",
    isNew: false,
    availabilityLabel: "Maintenant",
    intentions: ["verre d'abord", "rencontre ce soir", "discret"],
    isDiscreet: false,
    courtesyBadges: ["Profil courtois", "Vérifié"]
  },
  {
    id: "m11",
    username: "Lola",
    pseudo: "Lola",
    age: 21,
    city: "Toulouse",
    distance: "8 km",
    category: "Trans",
    genderIdentity: "FEMME_TRANS",
    description: "Jeune, libre et sans prise de tête. J'aime faire de nouvelles connaissances dans un cadre sécurisé.",
    images: [],
    verified: true,
    isVerified: true,
    online: true,
    onlineStatus: true,
    premium: true,
    isPremium: true,
    tags: ["Jeune", "Libre", "Authentique"],
    languages: ["Français", "Espagnol"],
    lastSeen: "En ligne",
    isNew: true,
    availabilityLabel: "Ce soir",
    intentions: ["discuter d'abord", "uniquement si feeling"],
    isDiscreet: true,
    courtesyBadges: ["Réponse rapide", "Vérifié"]
  },
  {
    id: "m12",
    username: "Clara",
    pseudo: "Clara",
    age: 34,
    city: "Genève",
    distance: "50 km",
    category: "Femme Cis",
    genderIdentity: "FEMME",
    description: "Indépendante et assumée. Je cherche quelqu'un qui sait ce qu'il veut, avec classe et respect.",
    images: [],
    verified: true,
    isVerified: true,
    online: false,
    onlineStatus: false,
    premium: true,
    isPremium: true,
    tags: ["Indépendante", "Classe", "Exigeante"],
    languages: ["Français", "Anglais"],
    lastSeen: "Hier soir",
    isNew: false,
    availabilityLabel: null,
    intentions: ["uniquement si feeling"],
    isDiscreet: false,
    courtesyBadges: ["Membre fiable"]
  }
];
