import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/fr/",
          "/about/",
          "/age-verification/",
          "/blog/",
          "/comparison/",
          "/comparisons/",
          "/comparaison/",
          "/faq/",
          "/free-dating-app/",
          "/freemium/",
          "/fr/",
          "/grindr-alternative/",
          "/guides/",
          "/lgbtq-dating-app/",
          "/moderation/",
          "/paris/",
          "/privacy/",
          "/safety/",
          "/support/",
          "/switzerland/",
          "/terms/",
          "/tinder-alternative/",
          "/uk/",
          "/us/",
          "/verified-dating-app/",
          "/site-rencontre-gay/",
          "/serious-dating-app/",
          "/rencontre/",
          "/dating/",
          "/freemium/",
          "/product/",
        ],
        disallow: [
          "/auth/",
          "/api/",
          "/dashboard/",
          "/messages/",
          "/decouvrir/",
          "/membres/",
          "/profiles/",
          "/notifications/",
          "/parametres/",
          "/favoris/",
          "/salons/",
          "/albums/",
          "/annonces/",
          "/blacklist/",
          "/forum/",
          "/verification/",
          "/admin/",
          "/premium/",
          "/pricing/",
          "/test-gay/",
          "/top-gay-cities/",
        ],
      },
    ],
    sitemap: "https://embir.xyz/sitemap.xml",
  };
}
