import { slugify } from "./utils";

const topics = [
  "comment faire un bon profil sur une application de rencontre",
  "application rencontre gratuite sans abonnement",
  "alternative a Tinder en France",
  "pourquoi les applications de rencontre fatiguent",
  "comment Embir pense la compatibilite",
  "le futur du dating freemium",
  "profils verifies et confiance",
  "rencontre pour toutes orientations",
  "dating mondial et inclusif",
  "sortir du swipe infini",
  "securite dans les rencontres modernes",
  "preferences et intentions claires",
  "communaute fondatrice Embir",
  "application mobile de rencontre a venir",
  "rencontre sans publicite au lancement",
  "rencontre serieuse et inclusive",
  "dating queer plus sain",
  "rencontre hetero sans bruit",
  "rencontre bi et preferences",
  "rencontre trans et respect",
  "premier message qui marche",
  "profil de rencontre rassurant",
  "photos et verification selfie",
  "compatibilite avant geolocalisation",
  "pourquoi le modele paywall fatigue",
  "freemium transparent explique",
  "moderation et securite dating",
  "rencontre a Paris autrement",
  "rencontre a Lyon autrement",
  "rencontre a Marseille autrement",
  "rencontre a Lille autrement",
  "rencontre a Bordeaux autrement",
  "rencontre a Toulouse autrement",
  "rencontre a Nantes autrement",
  "rencontre a Nice autrement",
  "rencontre a Strasbourg autrement",
  "rencontre a Montpellier autrement",
  "rencontre a Rennes autrement",
  "rencontre sans abonnement",
  "rencontre sans swipe toxique",
  "orientation et visibilite",
  "comment eviter les faux profils",
  "comment choisir une app inclusive",
  "relation durable et compatibilite",
  "dating casual transparent",
  "signaux de confiance en ligne",
  "privacy dans les apps de rencontre",
  "rencontre pour introvertis",
  "rencontre apres rupture",
  "rencontre apres 40 ans",
  "rencontre parents celibataires",
  "membre fondateur Embir",
  "not just a Grindr alternative",
  "application rencontre sans swipe",
  "trouver personnes compatibles",
  "rencontre pour introvertis",
  "profils verifies explication",
  "comment reperer faux profils",
  "vie privee applications rencontre",
  "signalement et blocage rencontre",
  "verification selfie explication",
  "red flags pour les femmes",
  "red flags pour les hommes",
  "rencontre apres divorce 40 ans",
  "rencontre apres 50 ans",
  "rencontre pour parents celibataires",
  "applications LGBTQ recommandees",
  "rencontre gay sans Grindr",
  "rencontre lesbienne alternatives",
  "rencontre bi inclusive",
  "rencontre trans securisee",
  "rencontre queer pour tous",
  "rencontre hetero repensee",
  "rencontre relation serieuse",
  "rencontre casual transparente",
  "fatigue applications rencontre",
  "qualite plutot que quantite",
  "premier message appli rencontre",
  "comment demarrer conversation",
  "conseils premier rendez-vous",
  "appel video avant rencontre",
  "exemples bio profil rencontre",
  "meilleures photos profil",
  "erreurs profil a eviter",
  "ghosting comment gerer",
  "comment gerer le rejet",
  "dependance apps rencontre",
  "pause applications rencontre",
  "retour dating apres pause",
  "apps gratuites vs payantes",
  "pourquoi gratuit marche mieux",
  "fatigue abonnements dating",
  "cout cache apps gratuites",
  "paywall apps alternatives",
  "modele freemium avantages",
  "application mobile tendances 2026",
  "futur rencontres en ligne",
  "compatibilite vs geolocalisation",
  "filtres orientation apps",
  "fonctionnalites securite dating",
  "signaler harcelement apps",
  "bloquer utilisateurs plateforme",
  "regles communautaires dating",
  "communaute fondatrice avantages",
  "acces anticipe application",
  "application sans publicite",
  "rencontre pour etudiants",
  "rencontre pour jeunes actifs",
  "rencontre pour freelances",
  "rencontre pour artistes",
  "rencontre pour professionnels",
  "rencontre a distance applications",
  "fuseaux horaires differents",
  "plateformes rencontre internationales",
  "conseils dating neurodivergent",
  "rencontre pour personnes anxieuses",
  "rencontre pour timides",
  "confiance en soi et dating",
  "sante mentale et dating",
  "comment les apps ont change les relations",
  "romance moderne ere numerique",
  "rencontrer des gens en ligne",
  "de la conversation au premier date",
  "conseils deuxieme rendez-vous",
  "quand devenir exclusif",
  "histoires de succes dating",
  "vraies connexions applications",
  "trouver sa communaute",
  "valeurs partagees en dating",
  "centres d interet profils rencontre",
  "dating et politique",
  "respecter les limites",
  "scene dating Paris 2026",
  "scene dating Lyon",
  "scene dating Marseille",
  "scene dating Bordeaux",
  "scene dating Lille",
  "culture du dating en France",
  "meilleures villes France pour dating",
  "rencontre  responsable",
  "rencontre  respectueuse",
  "rencontre  bienveillante",
  "rencontre  transparente",
  "rencontre  intentionnelle",
  "rencontre moderne  responsable",
  "rencontre moderne  respectueuse",
  "rencontre moderne  bienveillante",
  "rencontre moderne  transparente",
  "rencontre moderne  intentionnelle",
  "rencontre ethique  responsable",
  "rencontre ethique  respectueuse",
  "rencontre ethique  bienveillante",
  "rencontre ethique  transparente",
  "rencontre ethique  intentionnelle",
  "rencontre consciente  responsable",
  "rencontre consciente  respectueuse",
  "rencontre consciente  bienveillante",
  "rencontre consciente  transparente",
  "rencontre consciente  intentionnelle",
  "dating ethique pour tous",
  "dating ethique pour les jeunes",
  "dating ethique pour les adultes",
  "dating ethique pour les professionnels",
  "dating ethique pour les créatifs",
  "dating conscient pour tous",
  "dating conscient pour les jeunes",
  "dating conscient pour les adultes",
  "dating conscient pour les professionnels",
  "dating conscient pour les créatifs",
  "dating intentionnel pour tous",
  "dating intentionnel pour les jeunes",
  "dating intentionnel pour les adultes",
  "dating intentionnel pour les professionnels",
  "dating intentionnel pour les créatifs",
  "dating authentique pour tous",
  "dating authentique pour les jeunes",
  "dating authentique pour les adultes",
  "dating authentique pour les professionnels",
  "dating authentique pour les créatifs",
  "dating responsable pour tous",
  "dating responsable pour les jeunes",
  "dating responsable pour les adultes",
  "dating responsable pour les professionnels",
  "dating responsable pour les créatifs",
];

const exactSlugs: Record<string, string> = {
  "comment faire un bon profil sur une application de rencontre": "comment-faire-un-bon-profil-sur-une-application-de-rencontre",
  "application rencontre gratuite sans abonnement": "application-rencontre-gratuite-sans-abonnement",
  "alternative a Tinder en France": "alternative-a-tinder-en-france",
};

export const blogFr = topics.map((topic) => ({
  slug: exactSlugs[topic] ?? `fr-${slugify(topic)}`,
  locale: "fr" as const,
  title: topic.charAt(0).toUpperCase() + topic.slice(1),
  topic,
}));
