import { slugify } from "./utils";

const topics = [
  "free dating app no subscription",
  "how to write a good dating profile",
  "grindr alternative for real connections",
  "best dating platform for verified profiles in the US",
  "why American dating apps feel exhausting",
  "dating in New York with compatibility first",
  "dating in Los Angeles without endless swiping",
  "dating in Chicago with verified profiles",
  "dating in Houston with clearer preferences",
  "dating in Phoenix for every orientation",
  "dating in Philadelphia with safer discovery",
  "dating in San Antonio without early paywalls",
  "dating in San Diego with compatibility",
  "dating in Dallas with a founding community",
  "dating in San Jose with verified profiles",
  "dating in Austin beyond swipe culture",
  "dating in Jacksonville for all orientations",
  "dating in San Francisco with safety controls",
  "dating in Seattle with real preferences",
  "dating in Denver with compatibility filters",
  "dating in Boston with verified profiles",
  "dating in Miami without noisy apps",
  "dating in Atlanta through shared intent",
  "free at launch dating app in the United States",
  "future freemium dating model explained",
  "verified profiles in US dating apps",
  "orientation filters for modern dating",
  "preferences and compatibility in dating",
  "founding member dating community",
  "mobile dating app coming to the US",
  "not just a Grindr alternative",
  "not just a Tinder alternative",
  "how to avoid fake dating profiles",
  "dating app privacy in the United States",
  "safer first dates through verified profiles",
  "dating without opaque algorithms",
  "dating for every orientation in the US",
  "inclusive straight dating in the US",
  "LGBTQ dating with compatibility",
  "dating app fatigue and better matching",
  "free messaging during launch",
  "why paywalls hurt dating communities",
  "transparent freemium for dating safety",
  "moderation in modern dating apps",
  "profile quality beats swipe volume",
  "compatible people over nearby profiles",
  "how Embir plans mobile dating",
  "dating app for serious and casual intent",
  "relationship goals in dating profiles",
  "founder badge dating app",
  "dating in large US cities",
  "healthy dating community design",
  "Embir United States launch",
];

const exactSlugs: Record<string, string> = {
  "free dating app no subscription": "free-dating-app-no-subscription",
  "how to write a good dating profile": "how-to-write-a-good-dating-profile",
  "grindr alternative for real connections": "grindr-alternative-for-real-connections",
};

export const blogUs = topics.map((topic) => ({
  slug: exactSlugs[topic] ?? `us-${slugify(topic)}`,
  locale: "en" as const,
  market: "usa" as const,
  title: topic.charAt(0).toUpperCase() + topic.slice(1),
  topic,
}));
