import { slugify } from "./utils";

const topics = [
  "comment faire un bon profil sur une application de rencontre",
  "application rencontre gratuite sans abonnement",
  "alternative a Tinder en France",
  "pourquoi les applications de rencontre fatiguent",
  "comment Embir pense la compatibilite",
  "le futur du dating freemium",
  "profils verifies et confiance",
  "rencontre pour toutes orientations",
  "dating France UK USA",
  "sortir du swipe infini",
  "securite dans les rencontres modernes",
  "preferences et intentions claires",
  "communaute fondatrice Embir",
  "application mobile de rencontre a venir",
  "rencontre sans publicite au lancement",
  "rencontre serieuse et inclusive",
  "dating queer plus sain",
  "rencontre hetero sans bruit",
  "rencontre bi et preferences",
  "rencontre trans et respect",
  "premier message qui marche",
  "profil de rencontre rassurant",
  "photos et verification selfie",
  "compatibilite avant geolocalisation",
  "pourquoi le modele paywall fatigue",
  "freemium transparent explique",
  "moderation et securite dating",
  "rencontre a Paris autrement",
  "rencontre a Lyon autrement",
  "rencontre a Marseille autrement",
  "rencontre a Lille autrement",
  "rencontre a Bordeaux autrement",
  "rencontre a Toulouse autrement",
  "rencontre a Nantes autrement",
  "rencontre a Nice autrement",
  "rencontre a Strasbourg autrement",
  "rencontre a Montpellier autrement",
  "rencontre a Rennes autrement",
  "rencontre sans abonnement",
  "rencontre sans swipe toxique",
  "orientation et visibilite",
  "comment eviter les faux profils",
  "comment choisir une app inclusive",
  "relation durable et compatibilite",
  "dating casual transparent",
  "signaux de confiance en ligne",
  "privacy dans les apps de rencontre",
  "rencontre pour introvertis",
  "rencontre apres rupture",
  "rencontre apres 40 ans",
  "rencontre parents celibataires",
  "membre fondateur Embir",
  "not just a Grindr alternative",
];

const exactSlugs: Record<string, string> = {
  "comment faire un bon profil sur une application de rencontre": "comment-faire-un-bon-profil-sur-une-application-de-rencontre",
  "application rencontre gratuite sans abonnement": "application-rencontre-gratuite-sans-abonnement",
  "alternative a Tinder en France": "alternative-a-tinder-en-france",
};

export const blogFr = topics.map((topic) => ({
  slug: exactSlugs[topic] ?? `fr-${slugify(topic)}`,
  locale: "fr" as const,
  title: topic.charAt(0).toUpperCase() + topic.slice(1),
  topic,
}));
