import { slugify } from "./utils";

const topics = [
  "best dating platform for verified profiles in the UK",
  "why UK dating apps feel exhausting",
  "dating in London with compatibility first",
  "dating in Manchester without endless swiping",
  "dating in Birmingham with verified profiles",
  "dating in Leeds with clearer preferences",
  "dating in Glasgow for every orientation",
  "dating in Liverpool with safer discovery",
  "dating in Edinburgh without early paywalls",
  "dating in Bristol with compatibility",
  "dating in Sheffield with a founding community",
  "dating in Nottingham with verified profiles",
  "dating in Cardiff beyond swipe culture",
  "dating in Belfast for all orientations",
  "dating in Brighton with safety controls",
  "dating in Oxford with real preferences",
  "dating in Cambridge with compatibility filters",
  "dating in Southampton with verified profiles",
  "dating in Newcastle without noisy apps",
  "dating in York through shared intent",
  "free at launch dating app in the United Kingdom",
  "future freemium dating model in the UK",
  "verified profiles in UK dating apps",
  "orientation filters for UK dating",
  "preferences and compatibility in UK dating",
  "founding member dating community UK",
  "mobile dating app coming to the UK",
  "not just a Grindr alternative UK",
  "not just a Tinder alternative UK",
  "how to avoid fake dating profiles UK",
  "dating app privacy in the United Kingdom",
  "safer first dates through verified profiles UK",
  "dating without opaque algorithms UK",
  "dating for every orientation in the UK",
  "inclusive straight dating in the UK",
  "LGBTQ dating with compatibility UK",
  "dating app fatigue and better matching UK",
  "free messaging during launch UK",
  "why paywalls hurt dating communities UK",
  "transparent freemium for dating safety UK",
  "moderation in modern UK dating apps",
  "profile quality beats swipe volume UK",
  "compatible people over nearby profiles UK",
  "how Embir plans mobile dating UK",
  "dating app for serious and casual intent UK",
  "relationship goals in UK dating profiles",
  "founder badge dating app UK",
  "dating in large UK cities",
  "healthy dating community design UK",
  "Embir United Kingdom launch",
  "dating app without swipe culture UK",
  "finding compatible people UK",
  "dating for introverts in the UK",
  "verified vs unverified UK",
  "how to spot fake dating profiles UK",
  "dating app privacy UK",
  "why dating apps need human moderation UK",
  "selfie verification UK",
  "online dating red flags UK",
  "dating after divorce UK",
  "dating after 50 in the UK",
  "dating for single parents UK",
  "LGBTQ dating app recommendations UK",
  "gay dating without Grindr UK",
  "lesbian dating app alternatives UK",
  "bi dating inclusive platforms UK",
  "trans dating safe platforms UK",
  "queer dating UK",
  "straight dating reimagined UK",
  "dating for serious relationships UK",
  "casual dating transparent apps UK",
  "dating app burnout UK",
  "quality over quantity UK",
  "first message tips UK",
  "first date safety tips UK",
  "video call before dating UK",
  "dating app bio examples UK",
  "best photos dating profiles UK",
  "dating profile mistakes UK",
  "dating app ghosting UK",
  "how to deal with rejection UK",
  "free vs paid dating apps UK",
  "why free dating apps work better UK",
  "subscription fatigue UK",
  "hidden costs free dating apps UK",
  "dating app paywall alternatives UK",
  "freemium dating model benefits UK",
  "mobile dating app trends 2026 UK",
  "future of online dating UK",
  "compatibility based dating UK",
  "preference based matching UK",
  "inclusive dating platform features UK",
  "safety tools in dating apps UK",
  "community guidelines UK",
  "founder dating community benefits UK",
  "early access dating app UK",
  "dating app without ads UK",
  "dating for college students UK",
  "dating for young professionals UK",
  "dating for remote workers UK",
  "dating for creatives UK",
  "dating for tech workers UK",
  "long distance dating apps UK",
  "international dating platforms UK",
  "multilingual dating apps UK",
  "dating advice for neurodivergent UK",
  "dating for people with anxiety UK",
  "dating for shy people UK",
  "building confidence in dating UK",
  "dating and mental health UK",
  "how dating apps changed relationships UK",
  "modern romance UK",
  "meeting people online safely UK",
  "from chat to first date UK",
  "dating app success stories UK",
  "finding your community UK",
  "shared values in dating UK",
  "respecting boundaries UK",
  "dating in London vs Manchester",
  "dating culture in the UK",
  "British vs American dating apps",
  "London dating scene 2026",
  "Manchester dating scene",
  "Birmingham dating guide",
  "dating in Scotland",
  "dating in Wales",
  "dating in Northern Ireland",
  "best UK cities for dating",
  "dating in  relationships",
  "dating in  connections",
  "dating in  conversations",
  "dating in  experiences",
  "dating in  communities",
  "dating in modern  relationships",
  "dating in modern  connections",
  "dating in modern  conversations",
  "dating in modern  experiences",
  "dating in modern  communities",
  "dating in digital  relationships",
  "dating in digital  connections",
  "dating in digital  conversations",
  "dating in digital  experiences",
  "dating in digital  communities",
  "dating in healthy  relationships",
  "dating in healthy  connections",
  "dating in healthy  conversations",
  "dating in healthy  experiences",
  "dating in healthy  communities",
  "ethical dating habits",
  "ethical dating practices",
  "ethical dating approaches",
  "ethical dating choices",
  "ethical dating platforms",
  "conscious dating habits",
  "conscious dating practices",
  "conscious dating approaches",
  "conscious dating choices",
  "conscious dating platforms",
  "mindful dating habits",
  "mindful dating practices",
  "mindful dating approaches",
  "mindful dating choices",
  "mindful dating platforms",
  "authentic dating habits",
  "authentic dating practices",
  "authentic dating approaches",
  "authentic dating choices",
  "authentic dating platforms",
  "intentional dating habits",
  "intentional dating practices",
  "intentional dating approaches",
  "intentional dating choices",
  "intentional dating platforms",
];

export const blogUk = topics.map((topic) => ({
  slug: `uk-${slugify(topic)}`,
  locale: "en" as const,
  market: "uk" as const,
  title: topic.charAt(0).toUpperCase() + topic.slice(1),
  topic,
}));
