import { slugify } from "./utils";

const topics = [
  "free dating app no subscription",
  "how to write a good dating profile",
  "grindr alternative for real connections",
  "best dating platform for verified profiles in the US",
  "why American dating apps feel exhausting",
  "dating in New York with compatibility first",
  "dating in Los Angeles without endless swiping",
  "dating in Chicago with verified profiles",
  "dating in Houston with clearer preferences",
  "dating in Phoenix for every orientation",
  "dating in Philadelphia with safer discovery",
  "dating in San Antonio without early paywalls",
  "dating in San Diego with compatibility",
  "dating in Dallas with a founding community",
  "dating in San Jose with verified profiles",
  "dating in Austin beyond swipe culture",
  "dating in Jacksonville for all orientations",
  "dating in San Francisco with safety controls",
  "dating in Seattle with real preferences",
  "dating in Denver with compatibility filters",
  "dating in Boston with verified profiles",
  "dating in Miami without noisy apps",
  "dating in Atlanta through shared intent",
  "free at launch dating app in the United States",
  "future freemium dating model explained",
  "verified profiles in US dating apps",
  "orientation filters for modern dating",
  "preferences and compatibility in dating",
  "founding member dating community",
  "mobile dating app coming to the US",
  "not just a Grindr alternative",
  "not just a Tinder alternative",
  "how to avoid fake dating profiles",
  "dating app privacy in the United States",
  "safer first dates through verified profiles",
  "dating without opaque algorithms",
  "dating for every orientation in the US",
  "inclusive straight dating in the US",
  "LGBTQ dating with compatibility",
  "dating app fatigue and better matching",
  "free messaging during launch",
  "why paywalls hurt dating communities",
  "transparent freemium for dating safety",
  "moderation in modern dating apps",
  "profile quality beats swipe volume",
  "compatible people over nearby profiles",
  "how Embir plans mobile dating",
  "dating app for serious and casual intent",
  "relationship goals in dating profiles",
  "founder badge dating app",
  "dating in large US cities",
  "healthy dating community design",
  "Embir United States launch",
  "dating app without swipe culture",
  "finding compatible people on dating apps",
  "dating for introverts in the US",
  "verified vs unverified dating profiles",
  "how to spot fake dating profiles",
  "dating app privacy and safety tips",
  "why dating apps need human moderation",
  "selfie verification dating apps",
  "online dating red flags for women",
  "online dating red flags for men",
  "dating after divorce in your 40s",
  "dating after 50 in the US",
  "dating for single parents",
  "LGBTQ dating app recommendations",
  "gay dating without Grindr",
  "lesbian dating app alternatives",
  "bi dating inclusive platforms",
  "trans dating safe platforms",
  "queer dating for everyone",
  "straight dating reimagined",
  "dating for serious relationships",
  "casual dating transparent apps",
  "dating app burnout and how to fix it",
  "quality over quantity in dating",
  "first message tips for dating apps",
  "how to start a conversation on dating apps",
  "first date safety tips",
  "video call before dating",
  "dating app bio examples that work",
  "best photos for dating profiles",
  "dating profile mistakes to avoid",
  "dating app ghosting how to handle",
  "how to deal with rejection on dating apps",
  "dating app addiction signs",
  "taking a break from dating apps",
  "returning to dating after a break",
  "free dating vs paid dating apps",
  "why free dating apps work better",
  "subscription fatigue dating apps",
  "hidden costs of free dating apps",
  "dating app paywall alternatives",
  "freemium dating model benefits",
  "mobile dating app trends 2026",
  "future of online dating",
  "AI in dating apps pros and cons",
  "matching algorithms explained",
  "compatibility based dating vs location",
  "preference based matching",
  "orientation filters in dating apps",
  "inclusive dating platform features",
  "safety tools in dating apps",
  "reporting harassment on dating apps",
  "blocking users on dating platforms",
  "dating community guidelines",
  "founder dating community benefits",
  "early access dating app perks",
  "beta testing dating apps",
  "dating app feedback and improvement",
  "dating app without ads",
  "no spam dating platform",
  "clean dating app experience",
  "minimalist dating interface",
  "dating for college students",
  "dating for young professionals",
  "dating for remote workers",
  "dating for digital nomads",
  "dating for creatives and artists",
  "dating for tech workers",
  "dating for healthcare workers",
  "dating for teachers and educators",
  "long distance dating apps",
  "dating in different time zones",
  "international dating platforms",
  "multilingual dating apps",
  "dating advice for neurodivergent people",
  "dating for people with anxiety",
  "dating for shy people",
  "building confidence in dating",
  "dating and mental health",
  "self care while dating",
  "valentines day dating tips",
  "summer dating season tips",
  "new years resolution dating",
  "dating goals for 2026",
  "best time to join a dating app",
  "when to upgrade dating profile",
  "how dating apps changed relationships",
  "modern romance in digital age",
  "meeting people online safely",
  "from chat to first date",
  "second date tips",
  "when to become exclusive",
  "dating app success stories",
  "real connections on dating apps",
  "finding your community on dating platforms",
  "shared values in dating",
  "hobbies and interests in dating profiles",
  "dating someone with similar values",
  "environmentally conscious dating",
  "socially aware dating choices",
  "dating and politics conversations",
  "respecting boundaries in dating",
  "dating in New York vs Los Angeles",
  "dating in Chicago vs Miami",
  "dating culture in the United States",
  "European dating apps vs American",
  "dating in  relationships",
  "dating in  connections",
  "dating in  conversations",
  "dating in  experiences",
  "dating in  communities",
  "dating in modern  relationships",
  "dating in modern  connections",
  "dating in modern  conversations",
  "dating in modern  experiences",
  "dating in modern  communities",
  "dating in digital  relationships",
  "dating in digital  connections",
  "dating in digital  conversations",
  "dating in digital  experiences",
  "dating in digital  communities",
  "dating in healthy  relationships",
  "dating in healthy  connections",
  "dating in healthy  conversations",
  "dating in healthy  experiences",
  "dating in healthy  communities",
  "ethical dating habits",
  "ethical dating practices",
  "ethical dating approaches",
  "ethical dating choices",
  "ethical dating platforms",
  "conscious dating habits",
  "conscious dating practices",
  "conscious dating approaches",
  "conscious dating choices",
  "conscious dating platforms",
  "mindful dating habits",
  "mindful dating practices",
  "mindful dating approaches",
  "mindful dating choices",
  "mindful dating platforms",
  "authentic dating habits",
  "authentic dating practices",
  "authentic dating approaches",
  "authentic dating choices",
  "authentic dating platforms",
  "intentional dating habits",
  "intentional dating practices",
  "intentional dating approaches",
  "intentional dating choices",
  "intentional dating platforms",
];

const exactSlugs: Record<string, string> = {
  "free dating app no subscription": "free-dating-app-no-subscription",
  "how to write a good dating profile": "how-to-write-a-good-dating-profile",
  "grindr alternative for real connections": "grindr-alternative-for-real-connections",
};

export const blogUs = topics.map((topic) => ({
  slug: exactSlugs[topic] ?? `us-${slugify(topic)}`,
  locale: "en" as const,
  market: "usa" as const,
  title: topic.charAt(0).toUpperCase() + topic.slice(1),
  topic,
}));
