import { slugify } from "./utils";

const topics = [
  "best dating platform for verified profiles in the UK",
  "why UK dating apps feel exhausting",
  "dating in London with compatibility first",
  "dating in Manchester without endless swiping",
  "dating in Birmingham with verified profiles",
  "dating in Leeds with clearer preferences",
  "dating in Glasgow for every orientation",
  "dating in Liverpool with safer discovery",
  "dating in Edinburgh without early paywalls",
  "dating in Bristol with compatibility",
  "dating in Sheffield with a founding community",
  "dating in Nottingham with verified profiles",
  "dating in Cardiff beyond swipe culture",
  "dating in Belfast for all orientations",
  "dating in Brighton with safety controls",
  "dating in Oxford with real preferences",
  "dating in Cambridge with compatibility filters",
  "dating in Southampton with verified profiles",
  "dating in Newcastle without noisy apps",
  "dating in York through shared intent",
  "free at launch dating app in the United Kingdom",
  "future freemium dating model in the UK",
  "verified profiles in UK dating apps",
  "orientation filters for UK dating",
  "preferences and compatibility in UK dating",
  "founding member dating community UK",
  "mobile dating app coming to the UK",
  "not just a Grindr alternative UK",
  "not just a Tinder alternative UK",
  "how to avoid fake dating profiles UK",
  "dating app privacy in the United Kingdom",
  "safer first dates through verified profiles UK",
  "dating without opaque algorithms UK",
  "dating for every orientation in the UK",
  "inclusive straight dating in the UK",
  "LGBTQ dating with compatibility UK",
  "dating app fatigue and better matching UK",
  "free messaging during launch UK",
  "why paywalls hurt dating communities UK",
  "transparent freemium for dating safety UK",
  "moderation in modern UK dating apps",
  "profile quality beats swipe volume UK",
  "compatible people over nearby profiles UK",
  "how Embir plans mobile dating UK",
  "dating app for serious and casual intent UK",
  "relationship goals in UK dating profiles",
  "founder badge dating app UK",
  "dating in large UK cities",
  "healthy dating community design UK",
  "Embir United Kingdom launch",
];

export const blogUk = topics.map((topic) => ({
  slug: `uk-${slugify(topic)}`,
  locale: "en" as const,
  market: "uk" as const,
  title: topic.charAt(0).toUpperCase() + topic.slice(1),
  topic,
}));
