import { slugify } from "./utils";

const comparisons = [
  { app: "Tinder", slug: "tinder-alternative", locale: "en" as const, title: "Embir vs Tinder 2026 — Which App for Real, Verified Dating?" },
  { app: "Grindr", slug: "grindr-alternative", locale: "en" as const, title: "Embir vs Grindr — The Best Inclusive & Safe Alternative for Every Orientation" },
  { app: "Bumble", slug: "bumble-alternative", locale: "en" as const, title: "Embir vs Bumble 2026 — Full Comparison: Compatibility, Free Access, Inclusivity" },
  { app: "Hinge", slug: "hinge-alternative", locale: "en" as const, title: "Embir vs Hinge — Which App Delivers Real Compatibility & Verified Profiles?" },
  { app: "OkCupid", slug: "okcupid-alternative", locale: "en" as const, title: "Embir vs OkCupid 2026 — Free Dating, Verified Profiles & Inclusive Matching" },
  { app: "Match.com", slug: "match-alternative", locale: "en" as const, title: "Embir vs Match.com — Modern Compatibility vs Traditional Matchmaking" },
  { app: "Plenty of Fish", slug: "pof-alternative", locale: "en" as const, title: "Embir vs Plenty of Fish — Which Free Dating App Wins on Safety & Community?" },
  { app: "eHarmony", slug: "eharmony-alternative", locale: "en" as const, title: "Embir vs eHarmony" },
  { app: "Zoosk", slug: "zoosk-alternative", locale: "en" as const, title: "Embir vs Zoosk" },
  { app: "Coffee Meets Bagel", slug: "coffee-meets-bagel-alternative", locale: "en" as const, title: "Embir vs Coffee Meets Bagel" },
  { app: "Happn", slug: "happn-alternative", locale: "en" as const, title: "Embir vs Happn" },
  { app: "Feeld", slug: "feeld-alternative", locale: "en" as const, title: "Embir vs Feeld — Inclusive Dating, Verified Profiles & Real Connection" },
  { app: "HER", slug: "her-dating-alternative", locale: "en" as const, title: "Embir vs HER — LGBTQ+ Inclusive Dating with Verified Profiles & Deep Compatibility" },
  { app: "Scruff", slug: "scruff-alternative", locale: "en" as const, title: "Embir vs Scruff" },
  { app: "Badoo", slug: "badoo-alternative", locale: "en" as const, title: "Embir vs Badoo" },
  { app: "BLK", slug: "blk-alternative", locale: "en" as const, title: "Embir vs BLK" },
  { app: "Jack'd", slug: "jackd-alternative", locale: "en" as const, title: "Embir vs Jack'd" },
  { app: "Facebook Dating", slug: "facebook-dating-alternative", locale: "en" as const, title: "Embir vs Facebook Dating — Privacy-First Dating vs Social Media Integration" },
  { app: "Hinge vs Embir", slug: "hinge-vs-embir", locale: "en" as const, title: "Embir vs Hinge vs Embir" },
  { app: "Bumble vs Embir", slug: "bumble-vs-embir", locale: "en" as const, title: "Embir vs Bumble vs Embir" },
  { app: "Tinder vs Embir", slug: "tinder-vs-embir", locale: "en" as const, title: "Embir vs Tinder vs Embir" },
  { app: "OkCupid vs Embir", slug: "okcupid-vs-embir", locale: "en" as const, title: "Embir vs OkCupid vs Embir" },
  { app: "Grindr vs Embir", slug: "grindr-vs-embir", locale: "en" as const, title: "Embir vs Grindr vs Embir" },
  { app: "Match vs Embir", slug: "match-vs-embir", locale: "en" as const, title: "Embir vs Match vs Embir" },
  { app: "Fruitz vs Embir", slug: "fruitz-vs-embir", locale: "en" as const, title: "Embir vs Fruitz vs Embir" },
  { app: "Adopt vs Embir", slug: "adopt-vs-embir", locale: "en" as const, title: "Embir vs Adopt vs Embir" },
  { app: "Once vs Embir", slug: "once-vs-embir", locale: "en" as const, title: "Embir vs Once vs Embir" },
  { app: "Meetic vs Embir", slug: "meetic-vs-embir", locale: "en" as const, title: "Embir vs Meetic vs Embir" },
  { app: "Elite Rencontre vs Embir", slug: "elite-rencontre-vs-embir", locale: "en" as const, title: "Embir vs Elite Rencontre vs Embir" },
  { app: "Tinder in France", slug: "tinder-france", locale: "en" as const, title: "Embir vs Tinder in France" },
  { app: "Bumble in France", slug: "bumble-france", locale: "en" as const, title: "Embir vs Bumble in France" },
  { app: "Hinge in UK", slug: "hinge-uk", locale: "en" as const, title: "Embir vs Hinge in UK" },
  { app: "Bumble in UK", slug: "bumble-uk", locale: "en" as const, title: "Embir vs Bumble in UK" },
  { app: "Tinder in UK", slug: "tinder-uk", locale: "en" as const, title: "Embir vs Tinder in UK" },
  { app: "Hinge in USA", slug: "hinge-usa", locale: "en" as const, title: "Embir vs Hinge in USA" },
  { app: "Tinder in USA", slug: "tinder-usa", locale: "en" as const, title: "Embir vs Tinder in USA" },
  { app: "Tinder in Switzerland", slug: "tinder-suisse", locale: "en" as const, title: "Embir vs Tinder in Switzerland" },
  { app: "Bumble in Switzerland", slug: "bumble-suisse", locale: "en" as const, title: "Embir vs Bumble in Switzerland" },
  { app: "OkCupid alternative", slug: "okcupid-alternative-embir", locale: "en" as const, title: "Embir vs OkCupid alternative" },
  { app: "Coffee Meets Bagel alternative", slug: "cmb-alternative-embir", locale: "en" as const, title: "Embir vs Coffee Meets Bagel alternative" },
  { app: "Plenty of Fish alternative", slug: "pof-alternative-embir", locale: "en" as const, title: "Embir vs Plenty of Fish alternative" },
  { app: "Facebook Dating alternative", slug: "facebook-dating-alternative", locale: "en" as const, title: "Embir vs Facebook Dating alternative" },
  { app: "Tinder vs Bumble vs Hinge", slug: "tinder-bumble-hinge-comparison", locale: "en" as const, title: "Embir vs Tinder vs Bumble vs Hinge" },
  { app: "best dating app 2026", slug: "best-dating-app-2026", locale: "en" as const, title: "Embir vs Best Dating App 2026 — Why Verified Profiles & Compatibility Win" },
  { app: "best free dating app", slug: "best-free-dating-app-2026", locale: "en" as const, title: "Embir vs Best Free Dating App 2026 — Truly Free at Launch, No Hidden Paywalls" },
  { app: "best LGBTQ dating app", slug: "best-lgbtq-dating-app", locale: "en" as const, title: "Embir vs Best LGBTQ Dating App — Inclusive, Verified & Safe for Every Orientation" },
  { app: "best dating app for serious relationships", slug: "best-dating-serious-relationships", locale: "en" as const, title: "Embir vs Best Dating App for Serious Relationships" },
  { app: "best dating app for casual dating", slug: "best-dating-app-casual", locale: "en" as const, title: "Embir vs best dating app for casual dating" },
  { app: "best dating app over 40", slug: "best-dating-app-over-40", locale: "en" as const, title: "Embir vs best dating app over 40" },
  { app: "best dating app over 50", slug: "best-dating-app-over-50", locale: "en" as const, title: "Embir vs best dating app over 50" },
  { app: "best dating app for single parents", slug: "best-dating-app-single-parents", locale: "en" as const, title: "Embir vs best dating app for single parents" },
  { app: "best dating app for college students", slug: "best-dating-app-college", locale: "en" as const, title: "Embir vs best dating app for college students" },
  { app: "most popular dating app by country", slug: "popular-dating-app-by-country", locale: "en" as const, title: "Embir vs most popular dating app by country" },
  { app: "dating app with highest success rate", slug: "highest-success-dating-app", locale: "en" as const, title: "Embir vs dating app with highest success rate" },
  { app: "safest dating app", slug: "safest-dating-app", locale: "en" as const, title: "Embir vs Safest Dating App — Human Moderation, Verified Profiles & Real Trust" },
  { app: "most inclusive dating app", slug: "most-inclusive-dating-app", locale: "en" as const, title: "Embir vs Most Inclusive Dating App — Built for Every Orientation, Not a Niche" },
  { app: "best verified dating app", slug: "best-verified-dating-app", locale: "en" as const, title: "Embir vs Best Verified Dating App — Selfie Verification & Trust by Design" },
  { app: "best free messaging dating app", slug: "best-free-messaging-dating-app", locale: "en" as const, title: "Embir vs best free messaging dating app" },
  { app: "best dating app without paywall", slug: "best-dating-app-no-paywall", locale: "en" as const, title: "Embir vs Best Dating App Without Paywall — Free Messaging, No Credit Card Required" },
  { app: "cheapest dating app", slug: "cheapest-dating-app", locale: "en" as const, title: "Embir vs cheapest dating app" },
  { app: "most affordable dating app", slug: "affordable-dating-app", locale: "en" as const, title: "Embir vs most affordable dating app" },
  { app: "best dating app for introverts", slug: "best-dating-app-introverts", locale: "en" as const, title: "Embir vs best dating app for introverts" },
  { app: "best dating app for shy people", slug: "best-dating-app-shy", locale: "en" as const, title: "Embir vs best dating app for shy people" },
  { app: "best dating app for professionals", slug: "best-dating-app-professionals", locale: "en" as const, title: "Embir vs best dating app for professionals" },
  { app: "best dating app for remote workers", slug: "best-dating-app-remote", locale: "en" as const, title: "Embir vs best dating app for remote workers" },
  { app: "best dating app for creatives", slug: "best-dating-app-creatives", locale: "en" as const, title: "Embir vs best dating app for creatives" },
  { app: "dating app with best matching algorithm", slug: "best-matching-algorithm-dating", locale: "en" as const, title: "Embir vs dating app with best matching algorithm" },
  { app: "dating app with human moderation", slug: "human-moderation-dating-app", locale: "en" as const, title: "Embir vs Dating App with Human Moderation — Real People Review Reports" },
];
export const comparisonsEn = comparisons;
