const comparisons = [
  { app: "Tinder", slug: "alternative-tinder", locale: "fr" as const, title: "Embir vs Tinder 2026 : Quelle app choisir pour des rencontres réelles et vérifiées ?" },
  { app: "Grindr", slug: "alternative-grindr", locale: "fr" as const, title: "Embir vs Grindr : La meilleure alternative inclusive et safe pour toutes les orientations" },
  { app: "Bumble", slug: "alternative-bumble", locale: "fr" as const, title: "Embir vs Bumble 2026 : Comparaison complète — compatibilité, gratuité, inclusivité" },
  { app: "Hinge", slug: "alternative-hinge", locale: "fr" as const, title: "Embir vs Hinge : Quelle app offre vraie compatibilité et profils vérifiés ?" },
  { app: "OkCupid", slug: "alternative-okcupid", locale: "fr" as const, title: "Embir vs OkCupid 2026 : Rencontre gratuite, profils vérifiés et matching inclusif" },
  { app: "Match.com", slug: "alternative-match", locale: "fr" as const, title: "Embir vs Match.com : Compatibilité moderne vs matchmaking traditionnel" },
  { app: "Plenty of Fish", slug: "alternative-pof", locale: "fr" as const, title: "Embir vs Plenty of Fish : Quelle app gratuite gagne sur la sécurité et la communauté ?" },
  { app: "eHarmony", slug: "alternative-eharmony", locale: "fr" as const, title: "Embir vs eHarmony" },
  { app: "Zoosk", slug: "alternative-zoosk", locale: "fr" as const, title: "Embir vs Zoosk" },
  { app: "Coffee Meets Bagel", slug: "alternative-coffee-meets-bagel", locale: "fr" as const, title: "Embir vs Coffee Meets Bagel" },
  { app: "Happn", slug: "alternative-happn", locale: "fr" as const, title: "Embir vs Happn" },
  { app: "Feeld", slug: "alternative-feeld", locale: "fr" as const, title: "Embir vs Feeld : Rencontre inclusive, profils vérifiés et connexions réelles" },
  { app: "HER", slug: "alternative-her", locale: "fr" as const, title: "Embir vs HER : Rencontre LGBTQ+ inclusive avec profils vérifiés et compatibilité profonde" },
  { app: "Scruff", slug: "alternative-scruff", locale: "fr" as const, title: "Embir vs Scruff" },
  { app: "Badoo", slug: "alternative-badoo", locale: "fr" as const, title: "Embir vs Badoo" },
  { app: "Fruitz", slug: "fruitz-vs-embir", locale: "fr" as const, title: "Embir vs Fruitz" },
  { app: "Adopt", slug: "adopt-vs-embir", locale: "fr" as const, title: "Embir vs Adopt" },
  { app: "Once", slug: "once-vs-embir", locale: "fr" as const, title: "Embir vs Once" },
  { app: "Meetic", slug: "meetic-vs-embir", locale: "fr" as const, title: "Embir vs Meetic" },
  { app: "Elite Rencontre", slug: "elite-rencontre-vs-embir", locale: "fr" as const, title: "Embir vs Elite Rencontre" },
  { app: "Disons Demain", slug: "disons-demain-vs-embir", locale: "fr" as const, title: "Embir vs Disons Demain" },
  { app: "Bumble vs Embir", slug: "bumble-vs-embir", locale: "fr" as const, title: "Embir vs Bumble vs Embir" },
  { app: "Tinder vs Embir", slug: "tinder-vs-embir", locale: "fr" as const, title: "Embir vs Tinder vs Embir" },
  { app: "Grindr vs Embir", slug: "grindr-vs-embir", locale: "fr" as const, title: "Embir vs Grindr vs Embir" },
  { app: "Fruitz vs Embir", slug: "fruitz-vs-embir", locale: "fr" as const, title: "Embir vs Fruitz vs Embir" },
  { app: "Hinge vs Embir", slug: "hinge-vs-embir", locale: "fr" as const, title: "Embir vs Hinge vs Embir" },
  { app: "OkCupid vs Embir", slug: "okcupid-vs-embir", locale: "fr" as const, title: "Embir vs OkCupid vs Embir" },
  { app: "Meetic alternative", slug: "alternative-meetic", locale: "fr" as const, title: "Embir vs Meetic alternative" },
  { app: "Disons Demain alternative", slug: "alternative-disons-demain", locale: "fr" as const, title: "Embir vs Disons Demain alternative" },
  { app: "Once alternative", slug: "alternative-once", locale: "fr" as const, title: "Embir vs Once alternative" },
  { app: "Adopte alternative", slug: "alternative-adopte", locale: "fr" as const, title: "Embir vs Adopte alternative" },
  { app: "Fruitz alternative", slug: "alternative-fruitz", locale: "fr" as const, title: "Embir vs Fruitz alternative" },
  { app: "Bumble alternative", slug: "alternative-bumble-france", locale: "fr" as const, title: "Embir vs Bumble alternative" },
  { app: "Hinge alternative", slug: "alternative-hinge-france", locale: "fr" as const, title: "Embir vs Hinge alternative" },
  { app: "meilleure application rencontre 2026", slug: "meilleure-application-rencontre-2026", locale: "fr" as const, title: "Embir vs Meilleure App de Rencontre 2026 — Profils Vérifiés & Compatibilité" },
  { app: "meilleure appli rencontre gratuite", slug: "meilleure-appli-rencontre-gratuite", locale: "fr" as const, title: "Embir vs Meilleure Appli Rencontre Gratuite — Vraiment gratuit pour les connexions essentielles" },
  { app: "meilleure appli rencontre serieuse", slug: "meilleure-appli-rencontre-serieuse", locale: "fr" as const, title: "Embir vs meilleure appli rencontre serieuse" },
  { app: "meilleure appli rencontre LGBTQ", slug: "meilleure-appli-rencontre-lgbtq", locale: "fr" as const, title: "Embir vs Meilleure Appli Rencontre LGBTQ+ — Inclusive, Vérifiée & Safe" },
  { app: "appli rencontre plus securisee", slug: "appli-rencontre-plus-securisee", locale: "fr" as const, title: "Embir vs Appli Rencontre la Plus Sécurisée — signalement et blocage & Vrais Profils" },
  { app: "appli rencontre profils verifies", slug: "appli-rencontre-profils-verifies", locale: "fr" as const, title: "Embir vs Appli Rencontre Profils Vérifiés — Vérification Selfie & Confiance" },
  { app: "appli rencontre sans abonnement", slug: "appli-rencontre-sans-abonnement", locale: "fr" as const, title: "Embir vs appli rencontre sans abonnement" },
  { app: "appli rencontre sans paywall", slug: "appli-rencontre-sans-paywall", locale: "fr" as const, title: "Embir vs Appli Rencontre Sans Paywall — Gratuit, Pas de Carte Bancaire" },
  { app: "appli rencontre la moins chere", slug: "appli-rencontre-moins-chere", locale: "fr" as const, title: "Embir vs appli rencontre la moins chere" },
  { app: "appli rencontre pour introvertis", slug: "appli-rencontre-pour-introvertis", locale: "fr" as const, title: "Embir vs appli rencontre pour introvertis" },
  { app: "appli rencontre pour celibataires", slug: "appli-rencontre-pour-celibataires", locale: "fr" as const, title: "Embir vs appli rencontre pour celibataires" },
  { app: "appli rencontre pour profs", slug: "appli-rencontre-pour-profs", locale: "fr" as const, title: "Embir vs appli rencontre pour profs" },
  { app: "appli rencontre pour freelances", slug: "appli-rencontre-pour-freelances", locale: "fr" as const, title: "Embir vs appli rencontre pour freelances" },
  { app: "appli rencontre meilleur algorithme", slug: "appli-rencontre-meilleur-algorithme", locale: "fr" as const, title: "Embir vs appli rencontre meilleur algorithme" },
  { app: "appli rencontre signalement et blocage", slug: "appli-rencontre-moderation-humaine", locale: "fr" as const, title: "Embir vs Appli Rencontre signalement et blocage — Signalements enregistrés, blocage immédiat" },
  { app: "Tinder vs Bumble vs Hinge comparatif", slug: "comparatif-tinder-bumble-hinge", locale: "fr" as const, title: "Embir vs Tinder vs Bumble vs Hinge comparatif" },
  { app: "comparatif applications rencontre", slug: "comparatif-applications-rencontre", locale: "fr" as const, title: "Embir vs comparatif applications rencontre" },
  { app: "appli rencontre inclusive", slug: "appli-rencontre-inclusive", locale: "fr" as const, title: "Embir vs Appli Rencontre Inclusive — Toutes les Orientations, Vraie Communauté" },
];
export const comparisonsFr = comparisons;
