import { slugify } from "./utils";

const topics = [
  "choose a dating platform",
  "create a compatible dating profile",
  "set dating preferences",
  "use orientation filters",
  "date without infinite swiping",
  "avoid fake profiles",
  "verify a profile before meeting",
  "write a respectful first message",
  "plan a safer first date",
  "inclusive straight dating",
  "respectful gay dating",
  "inclusive lesbian dating",
  "bi dating without stereotypes",
  "respectful trans dating",
  "inclusive queer dating",
  "compatibility and values",
  "compatibility and intentions",
  "compatibility and lifestyle",
  "serious dating without pressure",
  "transparent casual dating",
  "founding dating community",
  "dating without ads",
  "transparent freemium model",
  "mobile dating app launch",
  "safety and moderation",
  "report toxic behavior",
  "protect dating privacy",
  "profile photos that build trust",
  "clear dating bio",
  "questions for better matches",
  "avoid dating app fatigue",
  "dating after a breakup",
  "dating after 40",
  "dating after 50",
  "dating for introverts",
  "dating for single parents",
  "dating in large cities",
  "dating in mid sized cities",
  "ethical dating",
  "dating without opaque algorithms",
  "online dating red flags",
  "online dating green flags",
  "conversation before meeting",
  "handle ghosting",
  "say no respectfully",
  "consent in dating",
  "move beyond Tinder",
  "alternative to swipe apps",
  "dating across the world",
  "verified profiles and trust",
  "relationship preferences",
  "orientation and visibility",
  "dating without subscription at launch",
  "become a founding member",
  "prepare your Embir profile",
  "find compatible people",
  "inclusive and safer dating",
  "dating for everyone",
  "compatibility before distance",
  "healthier dating community",
  "first date conversation starters",
  "how to tell if someone is interested",
  "reading body language on dates",
  "when to make the first move",
  "dating multiple people etiquette",
  "exclusive dating conversation",
  "meeting family and friends",
  "introducing partner to friends",
  "traveling together for the first time",
  "moving in together timeline",
  "long term relationship from dating app",
  "dating app statistics 2026",
  "most popular dating apps compared",
  "which dating app is best",
  "dating app demographics by city",
  "online dating market trends",
  "dating industry revenue models",
  "freemium vs subscription dating",
  "selfie verification technology",
  "how dating verification works",
  "biometric dating security",
  "identity verification apps",
  "catfish detection technology",
  "AI moderation in dating",
  "community guidelines enforcement",
  "dating platform trust signals",
  "dating app user behavior",
  "engagement metrics dating apps",
  "retention strategies dating",
  "conversion optimization dating",
  "dating app accessibility",
  "inclusive design in dating apps",
  "neurodiversity friendly dating",
  "dating for disabled people",
  "dating for LGBTQ elders",
  "dating for young adults 18-25",
  "interracial dating platforms",
  "interfaith dating considerations",
  "dating across cultures",
  "international dating tips",
  "language barriers in dating",
  "dating while traveling",
  "expat dating communities",
  "dating in a new city",
  "building social circle for dating",
  "meeting people organically",
  "online to offline dating transition",
  "speed dating vs apps",
];

export const guidesEn = topics.map((topic) => ({
  slug: slugify(topic),
  locale: "en" as const,
  title: `Guide: ${topic}`,
  topic,
}));
