import { slugify } from "./utils";

const topics = [
  "choisir une application de rencontre",
  "creer un profil de rencontre compatible",
  "definir ses preferences de rencontre",
  "utiliser les filtres orientation",
  "rencontrer sans swipe infini",
  "eviter les faux profils",
  "verifier un profil avant un date",
  "premier message respectueux",
  "premier rendez-vous securise",
  "rencontre hetero inclusive",
  "rencontre gay respectueuse",
  "rencontre lesbienne bienveillante",
  "rencontre bi sans stereotypes",
  "rencontre trans respectueuse",
  "rencontre queer inclusive",
  "compatibilite et valeurs",
  "compatibilite et intentions",
  "compatibilite et style de vie",
  "rencontre serieuse sans pression",
  "rencontre casual transparente",
  "communaute fondatrice",
  "dating sans publicite",
  "modele freemium transparent",
  "application mobile de rencontre",
  "securite et moderation",
  "signaler un comportement toxique",
  "proteger sa vie privee",
  "photos de profil qui rassurent",
  "bio de rencontre claire",
  "questions pour mieux matcher",
  "eviter la fatigue des apps",
  "rencontre apres rupture",
  "rencontre apres 40 ans",
  "rencontre apres 50 ans",
  "rencontre pour introvertis",
  "rencontre pour parents celibataires",
  "rencontre en grande ville",
  "rencontre en ville moyenne",
  "dating ethique",
  "dating sans algorithme opaque",
  "red flags en ligne",
  "green flags en ligne",
  "conversation avant rendez-vous",
  "gerer le ghosting",
  "dire non avec respect",
  "consentement dans le dating",
  "sortir du modele Tinder",
  "alternative au swipe",
  "rencontre partout dans le monde",
  "profils verifies et confiance",
  "preferences relationnelles",
  "orientation et visibilite",
  "rencontre sans abonnement au lancement",
  "devenir membre fondateur",
  "preparer son profil Embir",
  "trouver des personnes compatibles",
  "rencontre inclusive et securisee",
  "dating pour tous",
  "compatibilite avant distance",
  "communaute plus saine",
  "premier rendez-vous sujets de conversation",
  "savoir si quelqu un est interesse",
  "langage corporel en rendez-vous",
  "quand faire le premier pas",
  "etiquette des rencontres multiples",
  "conversation exclusivite",
  "presentation a la famille et amis",
  "voyager ensemble premiere fois",
  "emménager ensemble timing",
  "relation longue duree depuis appli",
  "statistiques applications rencontre 2026",
  "applications populaires comparees",
  "meilleure application rencontre",
  "demographie applications par ville",
  "tendances marche rencontre en ligne",
  "modeles economiques dating",
  "freemium vs abonnement dating",
  "technologie verification selfie",
  "securite biometricque rencontre",
  "verification identite applications",
  "detection catfish technologie",
  "IA moderation dans le dating",
  "regles communautaires enforcement",
  "signaux confiance plateforme",
  "comportement utilisateur dating",
  "metriques engagement apps",
  "strategies retention dating",
  "optimisation conversion dating",
  "accessibilite applications rencontre",
  "design inclusif apps",
  "rencontre neurodiverse",
  "rencontre pour personnes handicapees",
  "rencontre LGBTQ seniors",
  "rencontre jeunes adultes 18-25",
  "plateformes rencontre interraciales",
  "rencontre interreligieuse",
  "rencontre entre cultures",
  "conseils rencontre internationale",
  "barrieres linguistiques dating",
  "rencontre en voyage",
  "communautes expatriees dating",
  "rencontre dans nouvelle ville",
  "construire cercle social dating",
  "rencontrer des gens naturellement",
  "transition en ligne vers reel",
  "speed dating vs applications",
];

export const guidesFr = topics.map((topic) => ({
  slug: slugify(topic),
  locale: "fr" as const,
  title: `Guide : ${topic}`,
  topic,
}));
