import { slugify } from "./utils";

const topics = [
  "choisir une application de rencontre",
  "creer un profil de rencontre compatible",
  "definir ses preferences de rencontre",
  "utiliser les filtres orientation",
  "rencontrer sans swipe infini",
  "eviter les faux profils",
  "verifier un profil avant un date",
  "premier message respectueux",
  "premier rendez-vous securise",
  "rencontre hetero inclusive",
  "rencontre gay respectueuse",
  "rencontre lesbienne bienveillante",
  "rencontre bi sans stereotypes",
  "rencontre trans respectueuse",
  "rencontre queer inclusive",
  "compatibilite et valeurs",
  "compatibilite et intentions",
  "compatibilite et style de vie",
  "rencontre serieuse sans pression",
  "rencontre casual transparente",
  "communaute fondatrice",
  "dating sans publicite",
  "modele freemium transparent",
  "application mobile de rencontre",
  "securite et moderation",
  "signaler un comportement toxique",
  "proteger sa vie privee",
  "photos de profil qui rassurent",
  "bio de rencontre claire",
  "questions pour mieux matcher",
  "eviter la fatigue des apps",
  "rencontre apres rupture",
  "rencontre apres 40 ans",
  "rencontre apres 50 ans",
  "rencontre pour introvertis",
  "rencontre pour parents celibataires",
  "rencontre en grande ville",
  "rencontre en ville moyenne",
  "dating ethique",
  "dating sans algorithme opaque",
  "red flags en ligne",
  "green flags en ligne",
  "conversation avant rendez-vous",
  "gerer le ghosting",
  "dire non avec respect",
  "consentement dans le dating",
  "sortir du modele Tinder",
  "alternative au swipe",
  "rencontre France UK USA",
  "profils verifies et confiance",
  "preferences relationnelles",
  "orientation et visibilite",
  "rencontre sans abonnement au lancement",
  "devenir membre fondateur",
  "preparer son profil Embir",
  "trouver des personnes compatibles",
  "rencontre inclusive et securisee",
  "dating pour tous",
  "compatibilite avant distance",
  "communaute plus saine",
];

export const guidesFr = topics.map((topic) => ({
  slug: slugify(topic),
  locale: "fr" as const,
  title: `Guide : ${topic}`,
  topic,
}));
