import { slugify } from "./utils";

const topics = [
  "choose a dating platform",
  "create a compatible dating profile",
  "set dating preferences",
  "use orientation filters",
  "date without infinite swiping",
  "avoid fake profiles",
  "verify a profile before meeting",
  "write a respectful first message",
  "plan a safer first date",
  "inclusive straight dating",
  "respectful gay dating",
  "inclusive lesbian dating",
  "bi dating without stereotypes",
  "respectful trans dating",
  "inclusive queer dating",
  "compatibility and values",
  "compatibility and intentions",
  "compatibility and lifestyle",
  "serious dating without pressure",
  "transparent casual dating",
  "founding dating community",
  "dating without ads",
  "transparent freemium model",
  "mobile dating app launch",
  "safety and moderation",
  "report toxic behavior",
  "protect dating privacy",
  "profile photos that build trust",
  "clear dating bio",
  "questions for better matches",
  "avoid dating app fatigue",
  "dating after a breakup",
  "dating after 40",
  "dating after 50",
  "dating for introverts",
  "dating for single parents",
  "dating in large cities",
  "dating in mid sized cities",
  "ethical dating",
  "dating without opaque algorithms",
  "online dating red flags",
  "online dating green flags",
  "conversation before meeting",
  "handle ghosting",
  "say no respectfully",
  "consent in dating",
  "move beyond Tinder",
  "alternative to swipe apps",
  "dating across France UK USA",
  "verified profiles and trust",
  "relationship preferences",
  "orientation and visibility",
  "dating without subscription at launch",
  "become a founding member",
  "prepare your Embir profile",
  "find compatible people",
  "inclusive and safer dating",
  "dating for everyone",
  "compatibility before distance",
  "healthier dating community",
];

export const guidesEn = topics.map((topic) => ({
  slug: slugify(topic),
  locale: "en" as const,
  title: `Guide: ${topic}`,
  topic,
}));
