export const seoAuditThresholds = {
  sitemapUrls: 500,
  francePages: 80,
  usaPages: 120,
  ukPages: 90,
  switzerlandPages: 20,
  blogArticles: 150,
  guides: 120,
  comparisons: 40,
  hreflangPairs: 80,
  testedUrls: 100,
};

export const requiredSeoRoutes = [
  "/us",
  "/us/free-dating-app",
  "/us/tinder-alternative",
  "/us/grindr-alternative",
  "/us/lgbtq-dating-app",
  "/us/verified-dating-app",
  "/us/dating-app-new-york",
  "/us/dating-app-los-angeles",
  "/uk",
  "/uk/free-dating-app",
  "/uk/tinder-alternative",
  "/uk/grindr-alternative",
  "/uk/lgbtq-dating-app",
  "/uk/dating-app-london",
  "/uk/verified-dating-app",
  "/switzerland",
  "/switzerland/zurich",
  "/switzerland/geneva",
  "/fr/suisse",
  "/fr/suisse/geneve",
  "/comparison/grindr-vs-embir",
  "/freemium-model",
  "/fr/application-rencontre-gratuite",
  "/fr/rencontre-paris",
  "/fr/rencontre-gay-paris",
  "/fr/alternative-tinder",
  "/fr/alternative-grindr",
  "/fr/application-rencontre-sans-abonnement",
  "/fr/rencontre-lgbt",
  "/fr/profils-verifies",
  "/fr/modele-freemium",
  "/fr/gratuit-au-lancement",
  "/fr/rencontre/paris",
];
